# Generated by Django 5.1.3 on 2024-12-08 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesis', '0002_remove_comment_content_type_remove_comment_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cscomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='thesis.cspapers')),
            ],
        ),
    ]
